// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoConnect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number):Promise<string>;

export function DoDisconnect():Promise<string>;

export function ImportConfig(arg1:string):Promise<main.ConfigResult>;

export function IsConnected():Promise<boolean>;
