// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DoConnect(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['DoConnect'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function DoDisconnect() {
  return window['go']['main']['App']['DoDisconnect']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function ImportConfigFromDialog() {
  return window['go']['main']['App']['ImportConfigFromDialog']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListProfileItems() {
  return window['go']['main']['App']['ListProfileItems']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadDefaultConfig() {
  return window['go']['main']['App']['LoadDefaultConfig']();
}

export function LoadLastProfile() {
  return window['go']['main']['App']['LoadLastProfile']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function SaveLastProfile(arg1) {
  return window['go']['main']['App']['SaveLastProfile'](arg1);
}
